/** Django DRF v1 auth endpoints (relative to HMIS_API_URL, server-only). */
export const AUTH_API_PATHS = {
  signinRequestOtp: "/auth/signin/request-otp/",
  signinVerify: "/auth/signin/verify/",
  signinTotp: "/auth/signin/totp/",
  signinRecovery: "/auth/signin/recovery/",
  signinWebAuthnOptions: "/auth/signin/webauthn/options/",
  signinWebAuthnVerify: "/auth/signin/webauthn/verify/",
  signupRequestOtp: "/auth/signup/request-otp/",
  signupVerifyEmail: "/auth/signup/verify-email/",
  signupVerify: "/auth/signup/verify/",
  tokenRefresh: "/auth/token/refresh/",
  logout: "/auth/logout/",
  me: "/users/me/",
  userDetail: (userId: number) => `/users/${userId}/`,
  mfa: "/auth/mfa/",
  mfaTotpSetup: "/auth/mfa/totp/setup/",
  mfaTotpActivate: "/auth/mfa/totp/activate/",
  mfaTotpDeactivate: "/auth/mfa/totp/deactivate/",
  mfaWebAuthnRegisterOptions: "/auth/mfa/webauthn/register/options/",
  mfaWebAuthnRegister: "/auth/mfa/webauthn/register/",
  mfaWebAuthnDetail: (id: number) => `/auth/mfa/webauthn/${id}/`,
  mfaRecoveryCodesReveal: "/auth/mfa/recovery-codes/reveal/",
  mfaRecoveryCodesRegenerate: "/auth/mfa/recovery-codes/regenerate/",
} as const;
