/** Django DRF v1 occupational health endpoints (relative to HMIS_API_URL, server-only). */
export const OCCUPATIONAL_HEALTH_API_PATHS = {
  ohEncounters: "/oh-encounters/",
  employmentEpisodes: "/employment-episodes/",
  employmentEpisode: (uuid: string) => `/employment-episodes/${uuid}/`,
  employers: "/employers/",
  employerSites: "/employer-sites/",
  jobTitles: "/job-titles/",
  hazards: "/hazards/",
  hazardProfiles: "/hazard-profiles/",
  ohExaminations: "/oh-examinations/",
  ohExamination: (uuid: string) => `/oh-examinations/${uuid}/`,
  ohExamFindings: "/oh-exam-findings/",
  ohExamFinding: (uuid: string) => `/oh-exam-findings/${uuid}/`,
  fitnessAssessments: "/fitness-assessments/",
  fitnessAssessment: (uuid: string) => `/fitness-assessments/${uuid}/`,
  fitnessCertificates: "/fitness-certificates/",
  fitnessCertificate: (uuid: string) => `/fitness-certificates/${uuid}/`,
  iodCases: "/iod-cases/",
  iodCase: (uuid: string) => `/iod-cases/${uuid}/`,
  iodCaseStatutoryPack: (uuid: string) => `/iod-cases/${uuid}/statutory-pack/`,
  ohImmunisations: "/oh-immunisations/",
  ppeFitTests: "/ppe-fit-tests/",
  foodHandlerClearances: "/food-handler-clearances/",
  sickLeaveCertificates: "/sick-leave-certificates/",
  surveillanceRequirements: "/surveillance-requirements/",
  complianceDashboard: "/oh/compliance/dashboard/",
  complianceExtract: "/oh/compliance/extract/",
  campaignQueue: "/oh/campaign-queue/",
  hrFitness: "/oh/hr/fitness/",
  fitnessValidityAlerts: "/oh/fitness-validity-alerts/",
} as const;
