export const ROUTES = {
  home: "/",
  auth: "/auth",
  signup: "/signup",
  onboarding: "/onboarding",
  platformAdmin: "/platform-admin",
  platformAdminTenant: (tenantUuid: string) =>
    `/platform-admin/tenants/${tenantUuid}`,
  customers: "/customers",
  /** Default destination after successful sign-in / sign-up. */
  postAuth: "/customers",
  contacts: "/contacts",
  ourProducts: "/our-products",
  about: "/about",
  features: "/features",
  services: "/services",
  customerDetail: (customerId: string) => `/customers/${customerId}`,
  salesOrders: "/sales-orders",
  salesOrderDetail: (orderId: number | string) => `/sales-orders/${orderId}`,
  invoices: "/invoices",
  invoiceDetail: (invoiceId: number | string) => `/invoices/${invoiceId}`,
  payments: "/payments",
  paymentDetail: (paymentId: number | string) => `/payments/${paymentId}`,
  therapyPhysio: "/therapy/physio",
  therapySpeech: "/therapy/speech",
  therapyOccupational: "/therapy/occupational",
  therapyVisitDetail: (discipline: string, visitUuid: string) =>
    `/therapy/${discipline}/${visitUuid}`,
  inventoryStock: "/inventory/stock",
  inventoryStockDetail: (uuid: string) => `/inventory/stock/${uuid}`,
  inventoryProducts: "/inventory/products",
  inventoryProductDetail: (productUuid: string) =>
    `/inventory/products/${productUuid}`,
  inventoryPricelists: "/inventory/pricelists",
  inventoryPricelistDetail: (pricelistUuid: string) =>
    `/inventory/pricelists/${pricelistUuid}`,
  inventoryPurchaseOrders: "/inventory/purchase-orders",
  inventoryPurchaseOrderDetail: (uuid: string) =>
    `/inventory/purchase-orders/${uuid}`,
  inventoryInternalOrders: "/inventory/internal-orders",
  inventoryInternalOrderDetail: (uuid: string) =>
    `/inventory/internal-orders/${uuid}`,
  inventoryStockAdjustments: "/inventory/stock-adjustments",
  inventoryStockAdjustmentDetail: (uuid: string) =>
    `/inventory/stock-adjustments/${uuid}`,
  inventoryMovements: "/inventory/movements",
  inventoryMovementDetail: (uuid: string) => `/inventory/movements/${uuid}`,
  inventoryBatches: "/inventory/batches",
  inventoryBatchDetail: (uuid: string) => `/inventory/batches/${uuid}`,
  inventoryBatchNew: "/inventory/batches/new",
  activeVisits: "/active-visits",
  appointments: "/appointments",
  visitDetail: (uuid: string) => `/visits/${uuid}`,
  settings: "/settings",
  settingsAccount: "/settings/account",
  settingsOrganization: "/settings/organization",
  settingsVisitManagement: "/settings/visit-management",
  settingsFinanceOperations: "/settings/finance-operations",
  settingsUserManagement: "/settings/user-management",
  settingsModules: "/settings/modules",
  settingsModuleInventory: "/settings/modules/inventory",
  settingsIntegrations: "/settings/integrations",
  settingsIntegrationsEmail: "/settings/integrations/email",
} as const;

/** Paths served by web-new through the deploy gateway. */
export const WEB_NEW_ROUTE_PREFIXES = [
  ROUTES.home,
  ROUTES.auth,
  ROUTES.signup,
  ROUTES.onboarding,
  ROUTES.platformAdmin,
  ROUTES.customers,
  ROUTES.salesOrders,
  ROUTES.invoices,
  ROUTES.payments,
  ROUTES.therapyPhysio,
  ROUTES.therapySpeech,
  ROUTES.therapyOccupational,
  ROUTES.inventoryStock,
  ROUTES.inventoryProducts,
  ROUTES.inventoryPricelists,
  ROUTES.inventoryPurchaseOrders,
  ROUTES.inventoryInternalOrders,
  ROUTES.inventoryStockAdjustments,
  ROUTES.inventoryMovements,
  ROUTES.inventoryBatches,
  ROUTES.activeVisits,
  ROUTES.appointments,
  "/visits",
  ROUTES.settings,
  ROUTES.contacts,
  ROUTES.ourProducts,
  ROUTES.about,
  ROUTES.features,
  ROUTES.services,
] as const;

export const PUBLIC_ROUTES = [
  ROUTES.home,
  ROUTES.auth,
  ROUTES.signup,
  ROUTES.contacts,
  ROUTES.ourProducts,
  ROUTES.about,
  ROUTES.features,
  ROUTES.services,
] as const;

export const AUTH_ROUTES = [ROUTES.auth, ROUTES.signup] as const;

export const PROTECTED_ROUTES = [
  ROUTES.onboarding,
  ROUTES.platformAdmin,
  ROUTES.customers,
  ROUTES.salesOrders,
  ROUTES.invoices,
  ROUTES.payments,
  ROUTES.therapyPhysio,
  ROUTES.therapySpeech,
  ROUTES.therapyOccupational,
  ROUTES.inventoryStock,
  ROUTES.inventoryProducts,
  ROUTES.inventoryPricelists,
  ROUTES.inventoryPurchaseOrders,
  ROUTES.inventoryInternalOrders,
  ROUTES.inventoryStockAdjustments,
  ROUTES.inventoryMovements,
  ROUTES.inventoryBatches,
  ROUTES.activeVisits,
  ROUTES.appointments,
  "/visits",
  ROUTES.settings,
] as const;
