export const ROUTES = {
  home: "/",
  auth: "/auth",
  signup: "/signup",
  onboarding: "/onboarding",
  customers: "/customers",
  /** Default destination after successful sign-in / sign-up. */
  postAuth: "/customers",
  contacts: "/contacts",
  ourProducts: "/our-products",
  about: "/about",
  features: "/features",
  services: "/services",
  customerDetail: (customerId: string) => `/customers/${customerId}`,
  salesOrders: "/sales-orders",
  salesOrderDetail: (orderId: number | string) => `/sales-orders/${orderId}`,
  inventoryStock: "/inventory/stock",
  inventoryStockDetail: (uuid: string) => `/inventory/stock/${uuid}`,
  inventoryProducts: "/inventory/products",
  inventoryProductDetail: (productId: number | string) =>
    `/inventory/products/${productId}`,
  inventoryPurchaseOrders: "/inventory/purchase-orders",
  inventoryPurchaseOrderDetail: (uuid: string) =>
    `/inventory/purchase-orders/${uuid}`,
  inventoryInternalOrders: "/inventory/internal-orders",
  inventoryInternalOrderDetail: (uuid: string) =>
    `/inventory/internal-orders/${uuid}`,
  inventoryStockAdjustments: "/inventory/stock-adjustments",
  inventoryStockAdjustmentDetail: (uuid: string) =>
    `/inventory/stock-adjustments/${uuid}`,
  inventoryMovements: "/inventory/movements",
  inventoryMovementDetail: (uuid: string) => `/inventory/movements/${uuid}`,
  inventoryBatches: "/inventory/batches",
  inventoryBatchDetail: (uuid: string) => `/inventory/batches/${uuid}`,
  inventoryBatchNew: "/inventory/batches/new",
  activeVisits: "/active-visits",
  visitDetail: (uuid: string) => `/visits/${uuid}`,
  settings: "/settings",
  settingsAccount: "/settings/account",
  settingsOrganization: "/settings/organization",
  settingsVisitManagement: "/settings/visit-management",
  settingsFinanceOperations: "/settings/finance-operations",
  settingsUserManagement: "/settings/user-management",
  settingsModules: "/settings/modules",
  settingsModuleInventory: "/settings/modules/inventory",
} as const;

/** Paths served by web-new through the deploy gateway. */
export const WEB_NEW_ROUTE_PREFIXES = [
  ROUTES.home,
  ROUTES.auth,
  ROUTES.signup,
  ROUTES.onboarding,
  ROUTES.customers,
  ROUTES.salesOrders,
  ROUTES.inventoryStock,
  ROUTES.inventoryProducts,
  ROUTES.inventoryPurchaseOrders,
  ROUTES.inventoryInternalOrders,
  ROUTES.inventoryStockAdjustments,
  ROUTES.inventoryMovements,
  ROUTES.inventoryBatches,
  ROUTES.activeVisits,
  "/visits",
  ROUTES.settings,
  ROUTES.contacts,
  ROUTES.ourProducts,
  ROUTES.about,
  ROUTES.features,
  ROUTES.services,
] as const;

export const PUBLIC_ROUTES = [
  ROUTES.home,
  ROUTES.auth,
  ROUTES.signup,
  ROUTES.contacts,
  ROUTES.ourProducts,
  ROUTES.about,
  ROUTES.features,
  ROUTES.services,
] as const;

export const AUTH_ROUTES = [ROUTES.auth, ROUTES.signup] as const;

export const PROTECTED_ROUTES = [
  ROUTES.onboarding,
  ROUTES.customers,
  ROUTES.salesOrders,
  ROUTES.inventoryStock,
  ROUTES.inventoryProducts,
  ROUTES.inventoryPurchaseOrders,
  ROUTES.inventoryInternalOrders,
  ROUTES.inventoryStockAdjustments,
  ROUTES.inventoryMovements,
  ROUTES.inventoryBatches,
  ROUTES.activeVisits,
  "/visits",
  ROUTES.settings,
] as const;
