import { ROUTES } from "@/constants/routes";

export const LANDING_PROBLEM = {
  eyebrow: "The Problem",
  title: "What paper records are really costing you",
  description:
    "Paper doesn't fail all at once. It fails one entry at a time, until the small mistakes become costly problems.",
  items: [
    {
      title: "Stock disappears",
      description:
        "Medicines leave the shelf, but no one notices until supplies run out and patients can't get the treatment they need.",
    },
    {
      title: "Insurance and billing become difficult to manage",
      description:
        "Claims are rejected because billing rules were missed. Reconciling insurance payments takes hours of manual work. Staff struggle to see which invoices have been paid, which are still outstanding, and which services have already been provided without payment.",
    },
    {
      title: "Patient records are lost",
      description:
        "A misplaced file, damaged notebook, or missing page can erase critical patient history when it's needed most.",
    },
  ],
  summary:
    "Every missing entry, rejected claim, and lost record costs your clinic time, money, and trust.",
  closing:
    "Sigma brings your entire clinic together in one secure platform: patients, billing, insurance, inventory, and finances, from day one.",
} as const;

export const LANDING_TRUST = {
  title: "Why clinics trust Sigma with the switch",
  description:
    "If you've tried software before and gone back to paper, you're not alone. Most clinic software is built for hospitals with an IT department, not a team of three running a single site.",
  items: [
    {
      title: "No IT team required",
      description:
        "Sigma is configured for you and works from any browser. No server, no installation, no dedicated staff to maintain it.",
    },
    {
      title: "Live in under 8 hours",
      description:
        "Most clinics are trained and running the same day they sign up.",
    },
    {
      title: "Built for unreliable connectivity",
      description:
        "Sigma is designed to keep working through the connectivity conditions clinics actually have.",
    },
    {
      title: "You're never on your own",
      description:
        "Free setup support, and a team that answers when something breaks.",
    },
  ],
  closing: "200+ clinics have made the switch. None have gone back.",
} as const;

export const LANDING_CLINIC_COVER = {
  imageAlt: "Clinic staff caring for patients in a hospital setting",
  quote: "Built for the clinics that keep communities healthy. Every day.",
} as const;

export const LANDING_FEATURES = {
  title: "Run your clinic with confidence",
  description:
    "Stop waiting for someone to compile spreadsheets or count stock by hand. Sigma gives you the information you need, when you need it.",
  items: [
    {
      title: "See your revenue at a glance",
      description:
        "Track sales by day, week, month, or year so you always know how your clinic is performing.",
    },
    {
      title: "Understand where your income comes from",
      description:
        "Instantly see how much revenue comes from cash, insurance, or other payment methods.",
    },
    {
      title: "Monitor insurance claims",
      description:
        "Track submitted, approved, paid, pending, and rejected claims so you can follow up quickly and improve collections.",
    },
    {
      title: "Measure provider performance",
      description:
        "See the services delivered and revenue generated by each doctor, nurse, or care provider.",
    },
    {
      title: "Stay in control of your inventory",
      description:
        "Know what stock has been dispensed, what is running low, and what needs to be reordered.",
    },
    {
      title: "Prevent expired stock",
      description:
        "Get visibility into medicines and supplies approaching their expiry dates before they become a loss.",
    },
    {
      title: "Identify fast and slow moving items",
      description:
        "Understand which products need frequent replenishment and which are tying up valuable cash on your shelves.",
    },
  ],
  closing:
    "With Sigma, you spend less time searching for information and more time delivering quality patient care, while running a healthier, more profitable clinic.",
} as const;

export const LANDING_HOW_IT_WORKS = {
  title: "How it works",
  steps: [
    {
      title: "Book a free setup call",
      description:
        "We learn your workflow: patient flow, billing, stock, insurance.",
    },
    {
      title: "We configure Sigma for your clinic",
      description:
        "Your services, staff roles, billing rules, and inventory, set up for you.",
    },
    {
      title: "Your team is trained the same day",
      description:
        "No manual required. Most staff are comfortable within an hour.",
    },
    {
      title: "You're live in under 8 hours",
      description:
        "Most clinics see fewer billing disputes and clearer stock visibility within the first week.",
    },
  ],
} as const;

export const LANDING_PRICING = {
  eyebrow: "Pricing",
  title: "Priced so the clinics that need it most can actually afford it.",
  description:
    "We also offer subsidised access for public-sector facilities and NGO-run clinics.",
  plans: [
    {
      name: "Starter",
      price: "$29",
      period: "per month",
      features: [
        "Up to 3 staff accounts",
        "Patient records & visits",
        "Basic billing",
        "Email support",
      ],
      cta: "Get started",
      href: ROUTES.signup,
      highlighted: false,
    },
    {
      name: "Clinic",
      price: "$79",
      period: "per month",
      badge: "Most popular",
      features: [
        "Unlimited staff accounts",
        "Full EMR + billing + pharmacy",
        "MOH & donor reporting",
        "Free onboarding call",
        "WhatsApp support",
      ],
      cta: "Start free trial",
      href: ROUTES.signup,
      highlighted: true,
    },
    {
      name: "Network",
      price: "Custom",
      period: "multi-site pricing",
      features: [
        "Multiple clinic locations",
        "Centralised reporting",
        "API & DHIS2 integration",
        "Dedicated account manager",
      ],
      cta: "Talk to us",
      href: ROUTES.contacts,
      highlighted: false,
    },
  ],
} as const;

export const LANDING_FAQ = {
  eyebrow: "Common questions",
  title: "Things clinics usually ask us",
  items: [
    {
      question: "Do my staff need to be tech-savvy to use this?",
      answer:
        "No. Sigma is built for clinical staff, not IT staff. If your team uses a smartphone, they can use Sigma. The average staff member is comfortable navigating it within two hours.",
    },
    {
      question: "What if our internet goes down?",
      answer:
        "Sigma is cloud-based and works on any connection — including slow 3G. Most clinic workflows use very little data. We're also building offline capability, which will be available to all existing customers when it launches.",
    },
    {
      question: "We already have paper records going back years. What happens to them?",
      answer:
        "You don't need to digitise everything on day one. Most clinics start by entering new patients digitally, and gradually add historical records over time. We can also help with bulk import if you have existing spreadsheets.",
    },
    {
      question: "Is patient data secure?",
      answer:
        "Yes. Data is encrypted in transit and at rest, stored on servers in your region, and never shared or sold. We are compliant with national health data guidelines in our operating countries.",
    },
    {
      question: "What does the free trial include?",
      answer:
        "Full access to all Clinic plan features for 30 days. No credit card required. Your onboarding call is included. If you decide not to continue, we'll export all your data so you never lose anything.",
    },
  ],
} as const;

export const LANDING_FINAL_CTA = {
  title: "Your clinic deserves software that actually works here",
  description:
    "Join 200+ clinics across Africa, Asia, and the Americas who replaced paper chaos with a system built for their reality — not someone else's.",
  primaryCta: { label: "Start your free 30-day trial", href: ROUTES.signup },
  secondaryCta: { label: "Book a demo call", href: ROUTES.contacts },
} as const;
